version: '2'
services:

    nsp:
#        env_file: .env
        build:
            context: .
        image: nsp
        environment:
            - NSP=/nsp-lib
            - DATA_FILE=/input/train.json
            - INIT_DIR=/input_pdb
            - NUM_PROCESSES=3
        volumes:
            - ../nsp-lib:/nsp-lib
            - ../nsp-optim:/result
            - ../data:/input
            - ../nsp_result_full:/input_pdb
        working_dir: /result
