version: '2'
services:

    nsp:
#        env_file: .env
        build:
            context: .
        image: nsp
        environment:
            - NSP=/nsp-lib
            - DATA_FILE=/input/train_tmp.json
            - INIT_DIR=/input_pdb
            - NUM_PROCESSES=48
        volumes:
            - ../nsp-lib:/nsp-lib
            - ../nsp-optim_ya:/result
            - ../data:/input
            - ../nsp-result_ya:/input_pdb
        working_dir: /result
